global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: order-service-monitor

scrape_configs:
  - job_name: order-service
    metrics_path: /actuator/prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ['order-service:8080']
        labels:
          application: order-service
          environment: development

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: prometheus
          environment: development

  - job_name: tracing
    static_configs:
      - targets: ['tracing:3200']
        labels:
          application: tracing
          environment: development